integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
    - basic_auth:
        password: ${GRAFANA_PASSWORD}
        username: 61451
      url: https://prometheus-us-central1.grafana.net/api/prom/push
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ${GRAFANA_PASSWORD}
            username: 61451
          url: https://prometheus-us-central1.grafana.net/api/prom/push
      scrape_configs:
        - job_name: integrations/go
          static_configs:
            - targets:
                - localhost:8080
  global:
    scrape_interval: 15s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345