name: push
on: push
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Go test
        run: go test ./...

      - name: Build Docker image
        uses: docker/build-push-action@v2.2.0
        with:
          push: false
          tags: hatstand/shinywaffle:latest
